### ISSUE TITLE
The MM warning message after changes made to the model is unclear.

### ISSUE THREAD

**Issue by Unsongheroes** [INTO-CPS-Association/into-cps-application#135]
![image](https://user-images.githubusercontent.com/36032226/109615191-e7f3df80-7b33-11eb-91e8-afa318f56c56.png)

**Comment by clagms** [comment]
The student Navid found out that this warning message is incorrect: if a user changes the values of a parameter in the multimodel, it is not enough to edit and save a co-sim config.

This problem was reproduced in three other machines.

The workaround is to delete the co-sim config and re-generate it.

**Comment by kgpierce** [comment]
This message including the word "failed" makes students think things have gone wrong. I propose:

"It looks like the multi-model was changed. Press Edit and Save to accept this change."
