### ISSUE TITLE
Water tank 3D crashes when terminating

### ISSUE THREAD

**Issue by clegaard** [INTO-CPS-Association/into-cps-application#75]
![coe_fail_wartertank_conteusrefuseall](https://user-images.githubusercontent.com/18687499/75349495-30374c80-58a5-11ea-8db4-2a28eba62b02.png)
![coe_fail_wartertank_not_responding](https://user-images.githubusercontent.com/18687499/75349499-31687980-58a5-11ea-8393-793f35e4bb52.png)

It seems application is trying to reconnect to COE.

**Comment by clagms** [comment]
@clegaard 
Have you seen this?
![image](https://user-images.githubusercontent.com/871103/76141529-9a01e400-6065-11ea-85bf-9f015b90b9a5.png)

Is it perhaps related to it?
Or COE always crashing?
Does COE crash when you run the non-3D version?

**Comment by clegaard** [comment]
I think the fault is on the side of 20-sim, however the crash manages to screw up the application in the process. I think a FMU crashing is something that will happen once in while, so the application/coe should at least be able to handle this.

The repeated failed requests to the version of the COE is a heartbeat mechanism as far as i know. 

In my opinion there is a few usability issues:
1. The user is no told why the COE stopped
2. The user can not start a new COE (as far as i remember)
3. The user can not terminate the heartbeat-request mechanism.

**Comment by CThuleHansen** [comment]
It is an error due to 20-sim that crashes. 
In order to fix this in Maestro, it requires that every FMU is executed in isolation, which is the only way to handle such crashes. 

I do not disagree with @clegaard that maestro should handle it in a better fashion, but I do not consider it a high priority. 

However, there is certainly an interesting research potential of somehow considering crashing FMUs in a co-simulation. Is it allowed? Does it make sense for the co-simulation to continue in such a case? Perhaps it would make more sense to create an FMU that isolates another fmu such that it becomes generic?

**Comment by CThuleHansen** [comment]
Closing. Will be implemented in maestrov2.
